### ISSUE TITLE
Automatic removal of certain games from stats

### ISSUE THREAD

**Issue by tnan123** [michael1241/lichess4545-stats#5]
1. Specifically games played by marked cheaters that are forfeited. In running the end of season stats for example, I don't want to have to find all the IDs of those games to be added as arguments to be removed. 

2. It would be helpful for team games that are "casual" to be removed as well. Games that are restarted due to the claim victory feature sometimes become the gamelink used on the site.

**Comment by michael1241** [comment]
Resolved.
